package com.fathy.alfred.backend.internalcalls.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fathy.alfred.backend.internalcalls.domain.model.RequestData;

/**
 * POST /internal-calls/webhook/prepare's body - request-side data only, sent the moment the
 * reverse proxy intercepts a call, before WildFly has responded. {@code id} is generated by the
 * proxy itself - see InternalCallsService.receivePreparedCall, which falls back to generating one
 * server-side if this is blank. {@code sessionId}/{@code operationId} are the proxy's
 * X-Session-ID/X-Operation-Id header values - same blank-fallback treatment (stays null, never
 * invented server-side).
 */
public record PrepareInternalCallRequestDto(
        String id,
        @JsonProperty("original_url") String originalUrl,
        String url,
        String method,
        RequestData request,
        String timestamp,
        @JsonProperty("session_id") String sessionId,
        @JsonProperty("operation_id") String operationId
) {
}
