package com.fathy.alfred.backend.internalcalls.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.fathy.alfred.backend.internalcalls.domain.model.RequestData;

/**
 * POST /internal-calls/webhook/prepare's body - request-side data only, sent the moment the
 * reverse proxy intercepts a call, before WildFly has responded. {@code id} is generated by the
 * proxy itself - see InternalCallsService.receivePreparedCall, which falls back to generating one
 * server-side if this is blank. {@code sessionId}/{@code operationId} are the proxy's
 * X-Session-ID/X-Operation-Id header values - same blank-fallback treatment (stays null, never
 * invented server-side). {@code serviceName} is the project name proxy/log_and_route_reverse.py
 * resolved this flow's arrival port to (or its "unknown" bucket) - always sent, never blank.
 */
public record PrepareInternalCallRequestDto(
        String id,
        @JsonProperty("original_url") String originalUrl,
        String url,
        String method,
        RequestData request,
        String timestamp,
        @JsonProperty("session_id") String sessionId,
        @JsonProperty("operation_id") String operationId,
        @JsonProperty("service_name") String serviceName,
        @JsonProperty("resend_of") String resendOf,
        @JsonProperty("resend_edits") JsonNode resendEdits
) {
}
