package com.fathy.alfred.backend.calls.adapter.in.web.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fathy.alfred.backend.calls.domain.model.RequestData;

/**
 * POST /calls/webhook/prepare's body - request-side data only, sent the moment the proxy
 * intercepts a call, before the upstream has responded. {@code id} is generated by the proxy
 * itself (not returned by this endpoint) so the proxy never has to wait for a response before
 * knowing which call complete() will later resolve - see CallsService.receivePreparedCall, which
 * falls back to generating one server-side if this is blank (an old proxy build mid-rollout).
 * {@code sessionId}/{@code operationId} are the proxy's X-Session-ID/X-Operation-Id header values
 * (or a proxy-generated UUID if the client didn't send one) - same blank-fallback treatment.
 */
public record PrepareCallRequestDto(
        String id,
        @JsonProperty("original_url") String originalUrl,
        String url,
        String method,
        RequestData request,
        String timestamp,
        @JsonProperty("session_id") String sessionId,
        @JsonProperty("operation_id") String operationId
) {
}
