/**
 * Curated pool of single-glyph Unicode emoji (no skin-tone/gender modifiers, no flags -
 * anything that would render as more than one glyph across platforms was excluded) used as
 * profile avatars. Sourced from Unicode's own emoji-test.txt grouping data (the Smileys &
 * Emotion and Animals & Nature groups in full - the latter includes plants alongside animals
 * per Unicode's own grouping - plus the neutral single-codepoint entries from People & Body's
 * person/gesture/role/activity/sport subgroups) - not third-party icon artwork, so there's
 * nothing to download, license, or keep in sync with an external asset pack; every browser
 * already ships the glyphs via its own emoji font.
 */
export interface AvatarEmoji {
  readonly char: string;
  readonly name: string;
}

export const AVATAR_EMOJIS: readonly AvatarEmoji[] = [
  { char: '😀', name: 'grinning face' },
  { char: '😃', name: 'grinning face with big eyes' },
  { char: '😄', name: 'grinning face with smiling eyes' },
  { char: '😁', name: 'beaming face with smiling eyes' },
  { char: '😆', name: 'grinning squinting face' },
  { char: '😅', name: 'grinning face with sweat' },
  { char: '🤣', name: 'rolling on the floor laughing' },
  { char: '😂', name: 'face with tears of joy' },
  { char: '🙂', name: 'slightly smiling face' },
  { char: '🙃', name: 'upside-down face' },
  { char: '🫠', name: 'melting face' },
  { char: '😉', name: 'winking face' },
  { char: '😊', name: 'smiling face with smiling eyes' },
  { char: '😇', name: 'smiling face with halo' },
  { char: '🥰', name: 'smiling face with hearts' },
  { char: '😍', name: 'smiling face with heart-eyes' },
  { char: '🤩', name: 'star-struck' },
  { char: '😘', name: 'face blowing a kiss' },
  { char: '😗', name: 'kissing face' },
  { char: '☺️', name: 'smiling face' },
  { char: '😚', name: 'kissing face with closed eyes' },
  { char: '😙', name: 'kissing face with smiling eyes' },
  { char: '🥲', name: 'smiling face with tear' },
  { char: '😋', name: 'face savoring food' },
  { char: '😛', name: 'face with tongue' },
  { char: '😜', name: 'winking face with tongue' },
  { char: '🤪', name: 'zany face' },
  { char: '😝', name: 'squinting face with tongue' },
  { char: '🤑', name: 'money-mouth face' },
  { char: '🤗', name: 'smiling face with open hands' },
  { char: '🤭', name: 'face with hand over mouth' },
  { char: '🫢', name: 'face with open eyes and hand over mouth' },
  { char: '🫣', name: 'face with peeking eye' },
  { char: '🤫', name: 'shushing face' },
  { char: '🤔', name: 'thinking face' },
  { char: '🫡', name: 'saluting face' },
  { char: '🤐', name: 'zipper-mouth face' },
  { char: '🤨', name: 'face with raised eyebrow' },
  { char: '😐', name: 'neutral face' },
  { char: '😑', name: 'expressionless face' },
  { char: '😶', name: 'face without mouth' },
  { char: '🫥', name: 'dotted line face' },
  { char: '😏', name: 'smirking face' },
  { char: '😒', name: 'unamused face' },
  { char: '🙄', name: 'face with rolling eyes' },
  { char: '😬', name: 'grimacing face' },
  { char: '🤥', name: 'lying face' },
  { char: '🫨', name: 'shaking face' },
  { char: '😌', name: 'relieved face' },
  { char: '😔', name: 'pensive face' },
  { char: '😪', name: 'sleepy face' },
  { char: '🤤', name: 'drooling face' },
  { char: '😴', name: 'sleeping face' },
  { char: '😷', name: 'face with medical mask' },
  { char: '🤒', name: 'face with thermometer' },
  { char: '🤕', name: 'face with head-bandage' },
  { char: '🤢', name: 'nauseated face' },
  { char: '🤮', name: 'face vomiting' },
  { char: '🤧', name: 'sneezing face' },
  { char: '🥵', name: 'hot face' },
  { char: '🥶', name: 'cold face' },
  { char: '🥴', name: 'woozy face' },
  { char: '😵', name: 'face with crossed-out eyes' },
  { char: '🤯', name: 'exploding head' },
  { char: '🤠', name: 'cowboy hat face' },
  { char: '🥳', name: 'partying face' },
  { char: '🥸', name: 'disguised face' },
  { char: '😎', name: 'smiling face with sunglasses' },
  { char: '🤓', name: 'nerd face' },
  { char: '🧐', name: 'face with monocle' },
  { char: '😕', name: 'confused face' },
  { char: '🫤', name: 'face with diagonal mouth' },
  { char: '😟', name: 'worried face' },
  { char: '🙁', name: 'slightly frowning face' },
  { char: '☹️', name: 'frowning face' },
  { char: '😮', name: 'face with open mouth' },
  { char: '😯', name: 'hushed face' },
  { char: '😲', name: 'astonished face' },
  { char: '😳', name: 'flushed face' },
  { char: '🥺', name: 'pleading face' },
  { char: '🥹', name: 'face holding back tears' },
  { char: '😦', name: 'frowning face with open mouth' },
  { char: '😧', name: 'anguished face' },
  { char: '😨', name: 'fearful face' },
  { char: '😰', name: 'anxious face with sweat' },
  { char: '😥', name: 'sad but relieved face' },
  { char: '😢', name: 'crying face' },
  { char: '😭', name: 'loudly crying face' },
  { char: '😱', name: 'face screaming in fear' },
  { char: '😖', name: 'confounded face' },
  { char: '😣', name: 'persevering face' },
  { char: '😞', name: 'disappointed face' },
  { char: '😓', name: 'downcast face with sweat' },
  { char: '😩', name: 'weary face' },
  { char: '😫', name: 'tired face' },
  { char: '🥱', name: 'yawning face' },
  { char: '😤', name: 'face with steam from nose' },
  { char: '😡', name: 'enraged face' },
  { char: '😠', name: 'angry face' },
  { char: '🤬', name: 'face with symbols on mouth' },
  { char: '😈', name: 'smiling face with horns' },
  { char: '👿', name: 'angry face with horns' },
  { char: '💀', name: 'skull' },
  { char: '☠️', name: 'skull and crossbones' },
  { char: '💩', name: 'pile of poo' },
  { char: '🤡', name: 'clown face' },
  { char: '👹', name: 'ogre' },
  { char: '👺', name: 'goblin' },
  { char: '👻', name: 'ghost' },
  { char: '👽', name: 'alien' },
  { char: '👾', name: 'alien monster' },
  { char: '🤖', name: 'robot' },
  { char: '😺', name: 'grinning cat' },
  { char: '😸', name: 'grinning cat with smiling eyes' },
  { char: '😹', name: 'cat with tears of joy' },
  { char: '😻', name: 'smiling cat with heart-eyes' },
  { char: '😼', name: 'cat with wry smile' },
  { char: '😽', name: 'kissing cat' },
  { char: '🙀', name: 'weary cat' },
  { char: '😿', name: 'crying cat' },
  { char: '😾', name: 'pouting cat' },
  { char: '🙈', name: 'see-no-evil monkey' },
  { char: '🙉', name: 'hear-no-evil monkey' },
  { char: '🙊', name: 'speak-no-evil monkey' },
  { char: '👶', name: 'baby' },
  { char: '🧒', name: 'child' },
  { char: '👦', name: 'boy' },
  { char: '👧', name: 'girl' },
  { char: '🧑', name: 'person' },
  { char: '👱', name: 'person: blond hair' },
  { char: '👨', name: 'man' },
  { char: '🧔', name: 'person: beard' },
  { char: '👩', name: 'woman' },
  { char: '🧓', name: 'older person' },
  { char: '👴', name: 'old man' },
  { char: '👵', name: 'old woman' },
  { char: '🙍', name: 'person frowning' },
  { char: '🙎', name: 'person pouting' },
  { char: '🙅', name: 'person gesturing NO' },
  { char: '🙆', name: 'person gesturing OK' },
  { char: '💁', name: 'person tipping hand' },
  { char: '🙋', name: 'person raising hand' },
  { char: '🧏', name: 'deaf person' },
  { char: '🙇', name: 'person bowing' },
  { char: '🤦', name: 'person facepalming' },
  { char: '🤷', name: 'person shrugging' },
  { char: '👮', name: 'police officer' },
  { char: '🕵️', name: 'detective' },
  { char: '💂', name: 'guard' },
  { char: '🥷', name: 'ninja' },
  { char: '👷', name: 'construction worker' },
  { char: '🫅', name: 'person with crown' },
  { char: '🤴', name: 'prince' },
  { char: '👸', name: 'princess' },
  { char: '👳', name: 'person wearing turban' },
  { char: '👲', name: 'person with skullcap' },
  { char: '🧕', name: 'woman with headscarf' },
  { char: '🤵', name: 'person in tuxedo' },
  { char: '👰', name: 'person with veil' },
  { char: '🤰', name: 'pregnant woman' },
  { char: '🫃', name: 'pregnant man' },
  { char: '🫄', name: 'pregnant person' },
  { char: '🤱', name: 'breast-feeding' },
  { char: '👼', name: 'baby angel' },
  { char: '🎅', name: 'Santa Claus' },
  { char: '🤶', name: 'Mrs. Claus' },
  { char: '🦸', name: 'superhero' },
  { char: '🦹', name: 'supervillain' },
  { char: '🧙', name: 'mage' },
  { char: '🧚', name: 'fairy' },
  { char: '🧛', name: 'vampire' },
  { char: '🧜', name: 'merperson' },
  { char: '🧝', name: 'elf' },
  { char: '🧞', name: 'genie' },
  { char: '🧟', name: 'zombie' },
  { char: '🧌', name: 'troll' },
  { char: '💆', name: 'person getting massage' },
  { char: '💇', name: 'person getting haircut' },
  { char: '🚶', name: 'person walking' },
  { char: '🧍', name: 'person standing' },
  { char: '🧎', name: 'person kneeling' },
  { char: '🏃', name: 'person running' },
  { char: '💃', name: 'woman dancing' },
  { char: '🕺', name: 'man dancing' },
  { char: '🕴️', name: 'person in suit levitating' },
  { char: '👯', name: 'people with bunny ears' },
  { char: '🧖', name: 'person in steamy room' },
  { char: '🧗', name: 'person climbing' },
  { char: '🤺', name: 'person fencing' },
  { char: '🏇', name: 'horse racing' },
  { char: '⛷️', name: 'skier' },
  { char: '🏂', name: 'snowboarder' },
  { char: '🏌️', name: 'person golfing' },
  { char: '🏄', name: 'person surfing' },
  { char: '🚣', name: 'person rowing boat' },
  { char: '🏊', name: 'person swimming' },
  { char: '⛹️', name: 'person bouncing ball' },
  { char: '🏋️', name: 'person lifting weights' },
  { char: '🚴', name: 'person biking' },
  { char: '🚵', name: 'person mountain biking' },
  { char: '🤸', name: 'person cartwheeling' },
  { char: '🤼', name: 'people wrestling' },
  { char: '🤽', name: 'person playing water polo' },
  { char: '🤾', name: 'person playing handball' },
  { char: '🤹', name: 'person juggling' },
  { char: '🐵', name: 'monkey face' },
  { char: '🐒', name: 'monkey' },
  { char: '🦍', name: 'gorilla' },
  { char: '🦧', name: 'orangutan' },
  { char: '🐶', name: 'dog face' },
  { char: '🐕', name: 'dog' },
  { char: '🦮', name: 'guide dog' },
  { char: '🐩', name: 'poodle' },
  { char: '🐺', name: 'wolf' },
  { char: '🦊', name: 'fox' },
  { char: '🦝', name: 'raccoon' },
  { char: '🐱', name: 'cat face' },
  { char: '🐈', name: 'cat' },
  { char: '🦁', name: 'lion' },
  { char: '🐯', name: 'tiger face' },
  { char: '🐅', name: 'tiger' },
  { char: '🐆', name: 'leopard' },
  { char: '🐴', name: 'horse face' },
  { char: '🫎', name: 'moose' },
  { char: '🫏', name: 'donkey' },
  { char: '🐎', name: 'horse' },
  { char: '🦄', name: 'unicorn' },
  { char: '🦓', name: 'zebra' },
  { char: '🦌', name: 'deer' },
  { char: '🦬', name: 'bison' },
  { char: '🐮', name: 'cow face' },
  { char: '🐂', name: 'ox' },
  { char: '🐃', name: 'water buffalo' },
  { char: '🐄', name: 'cow' },
  { char: '🐷', name: 'pig face' },
  { char: '🐖', name: 'pig' },
  { char: '🐗', name: 'boar' },
  { char: '🐽', name: 'pig nose' },
  { char: '🐏', name: 'ram' },
  { char: '🐑', name: 'ewe' },
  { char: '🐐', name: 'goat' },
  { char: '🐪', name: 'camel' },
  { char: '🐫', name: 'two-hump camel' },
  { char: '🦙', name: 'llama' },
  { char: '🦒', name: 'giraffe' },
  { char: '🐘', name: 'elephant' },
  { char: '🦣', name: 'mammoth' },
  { char: '🦏', name: 'rhinoceros' },
  { char: '🦛', name: 'hippopotamus' },
  { char: '🐭', name: 'mouse face' },
  { char: '🐁', name: 'mouse' },
  { char: '🐀', name: 'rat' },
  { char: '🐹', name: 'hamster' },
  { char: '🐰', name: 'rabbit face' },
  { char: '🐇', name: 'rabbit' },
  { char: '🐿️', name: 'chipmunk' },
  { char: '🦫', name: 'beaver' },
  { char: '🦔', name: 'hedgehog' },
  { char: '🦇', name: 'bat' },
  { char: '🐻', name: 'bear' },
  { char: '🐨', name: 'koala' },
  { char: '🐼', name: 'panda' },
  { char: '🦥', name: 'sloth' },
  { char: '🦦', name: 'otter' },
  { char: '🦨', name: 'skunk' },
  { char: '🦘', name: 'kangaroo' },
  { char: '🦡', name: 'badger' },
  { char: '🐾', name: 'paw prints' },
  { char: '🦃', name: 'turkey' },
  { char: '🐔', name: 'chicken' },
  { char: '🐓', name: 'rooster' },
  { char: '🐣', name: 'hatching chick' },
  { char: '🐤', name: 'baby chick' },
  { char: '🐥', name: 'front-facing baby chick' },
  { char: '🐦', name: 'bird' },
  { char: '🐧', name: 'penguin' },
  { char: '🕊️', name: 'dove' },
  { char: '🦅', name: 'eagle' },
  { char: '🦆', name: 'duck' },
  { char: '🦢', name: 'swan' },
  { char: '🦉', name: 'owl' },
  { char: '🦤', name: 'dodo' },
  { char: '🪶', name: 'feather' },
  { char: '🦩', name: 'flamingo' },
  { char: '🦚', name: 'peacock' },
  { char: '🦜', name: 'parrot' },
  { char: '🪽', name: 'wing' },
  { char: '🪿', name: 'goose' },
  { char: '🐸', name: 'frog' },
  { char: '🐊', name: 'crocodile' },
  { char: '🐢', name: 'turtle' },
  { char: '🦎', name: 'lizard' },
  { char: '🐍', name: 'snake' },
  { char: '🐲', name: 'dragon face' },
  { char: '🐉', name: 'dragon' },
  { char: '🦕', name: 'sauropod' },
  { char: '🦖', name: 'T-Rex' },
  { char: '🐳', name: 'spouting whale' },
  { char: '🐋', name: 'whale' },
  { char: '🐬', name: 'dolphin' },
  { char: '🦭', name: 'seal' },
  { char: '🐟', name: 'fish' },
  { char: '🐠', name: 'tropical fish' },
  { char: '🐡', name: 'blowfish' },
  { char: '🦈', name: 'shark' },
  { char: '🐙', name: 'octopus' },
  { char: '🐚', name: 'spiral shell' },
  { char: '🪸', name: 'coral' },
  { char: '🪼', name: 'jellyfish' },
  { char: '🐌', name: 'snail' },
  { char: '🦋', name: 'butterfly' },
  { char: '🐛', name: 'bug' },
  { char: '🐜', name: 'ant' },
  { char: '🐝', name: 'honeybee' },
  { char: '🪲', name: 'beetle' },
  { char: '🐞', name: 'lady beetle' },
  { char: '🦗', name: 'cricket' },
  { char: '🪳', name: 'cockroach' },
  { char: '🕷️', name: 'spider' },
  { char: '🕸️', name: 'spider web' },
  { char: '🦂', name: 'scorpion' },
  { char: '🦟', name: 'mosquito' },
  { char: '🪰', name: 'fly' },
  { char: '🪱', name: 'worm' },
  { char: '🦠', name: 'microbe' },
  { char: '💐', name: 'bouquet' },
  { char: '🌸', name: 'cherry blossom' },
  { char: '💮', name: 'white flower' },
  { char: '🪷', name: 'lotus' },
  { char: '🏵️', name: 'rosette' },
  { char: '🌹', name: 'rose' },
  { char: '🥀', name: 'wilted flower' },
  { char: '🌺', name: 'hibiscus' },
  { char: '🌻', name: 'sunflower' },
  { char: '🌼', name: 'blossom' },
  { char: '🌷', name: 'tulip' },
  { char: '🪻', name: 'hyacinth' },
  { char: '🌱', name: 'seedling' },
  { char: '🪴', name: 'potted plant' },
  { char: '🌲', name: 'evergreen tree' },
  { char: '🌳', name: 'deciduous tree' },
  { char: '🌴', name: 'palm tree' },
  { char: '🌵', name: 'cactus' },
  { char: '🌾', name: 'sheaf of rice' },
  { char: '🌿', name: 'herb' },
  { char: '☘️', name: 'shamrock' },
  { char: '🍀', name: 'four leaf clover' },
  { char: '🍁', name: 'maple leaf' },
  { char: '🍂', name: 'fallen leaf' },
  { char: '🍃', name: 'leaf fluttering in wind' },
  { char: '🪹', name: 'empty nest' },
  { char: '🪺', name: 'nest with eggs' },
  { char: '🍄', name: 'mushroom' },
];

/** A fresh random pick - used for a new profile's starting avatar, and the picker's "Randomize" button. */
export function randomAvatarEmoji(): AvatarEmoji {
  return AVATAR_EMOJIS[Math.floor(Math.random() * AVATAR_EMOJIS.length)];
}
